### ISSUE TITLE
code is not working 

### ISSUE THREAD

**Issue by shadow1666** [marvincorreia/superset-keycloak#1]
hi , i think the code is not working ,

**Comment by marvincorreia** [comment]
Hi @shadow1666 can you provide more info about what is going wrong on your side, maybe I can help you, so I tried to clone this project in a clean directory and I realize that a comment on file client_secret.example.json "check this [commit](https://github.com/marvincorreia/superset-keycloak/commit/abdc393db38051a169a16dc14e31cf618f0e9057)" is getting some problem when python read the file so you need to pull latest changes or remove it on your client_secret.json, ensure you read the steps to run the project.

**Comment by shadow1666** [comment]
hi marcvin , i did the required changes but the problem persists can you clarify what steps  you followed ? and what credentials that you added and changed in the files ?

**Comment by marvincorreia** [comment]
The project requires knowledge about keycloak, I don't mention how to install this software because it's not the focus of this project, but I made the client available where it can be loaded into the keycloak for the integration to work, the rest of the tips are in the README.md
