### ISSUE TITLE
image not found superset-keycloak

### ISSUE THREAD

**Issue by daymonoid** [marvincorreia/superset-keycloak#2]
Hi Marvin!
file:docker-compose.prod.yml contain x-superset-image: &superset-image **superset-keycloak**
Please show Dockerfile for PRODUCTION or it`s bulding from existing Dockerfile from apache/superset:latest-dev

**Comment by marvincorreia** [comment]
Hi @daymonoid, I configured the docker-compose.prod.yml to build the image automatically in case it doesn't exist, using the Dockerfile, the directive ```build: .``` mean to use the Dockerfile on the root of the project to build the ```superset-keycloak``` image, use this command to build the image ```docker-compose -f docker-compose.prod.yml build```

**Comment by daymonoid** [comment]
Thank you!
Second questions. Can Dockerfile for production build working image from apache/superset:latest non dev source or it's important to use superset:latest-dev?

**Comment by marvincorreia** [comment]
Oww nice question, I think maybe the `apache/superset:latest` can be the best choice for production but I don't test it yet...
