### ISSUE TITLE
Non root image

### ISSUE THREAD

**Issue by daymonoid** [marvincorreia/superset-keycloak#3]
Hi @marvincorreia!
Can you add in Dockerfile install requirements to use this image as non root(without feature installtion under root)?

**Comment by marvincorreia** [comment]
Hi @daymonoid, In the Dockerfile of this project I just base on the original superset image and I copy some assets and also scripts that are useful to run the program, but if you want to change this configuration you are free to do that.
You can find the original Dockerfile [here](https://github.com/apache/superset/blob/master/Dockerfile), have a nice day!
